version: '3.8'

services:
  web:
    build: .
    environment:
      - JWT_SECRET_KEY=sua-chave-secreta-aqui
#    volumes:
#      - .:/app
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
